# RFC MP Plus starting institutions. Compatible with Civ4's Python 2.4.
from CvPythonExtensions import CyGlobalContext

# Columns: Government, Legitimacy, Labor, Military, Religion.
# These are preferences; unavailable choices use the fallbacks below.
PROFILES = {
    "CIVILIZATION_EGYPT": ("MONARCHY", "DESPOTISM", "SLAVERY", "MILITIA", "STATE_RELIGION"),
    "CIVILIZATION_INDIA": ("MONARCHY", "DESPOTISM", "SERFDOM", "MILITIA", "STATE_RELIGION"),
    "CIVILIZATION_CHINA": ("MONARCHY", "DESPOTISM", "SERFDOM", "MILITIA", "ANCESTOR_CULT"),
    "CIVILIZATION_BABYLONIA": ("MONARCHY", "DESPOTISM", "SLAVERY", "MILITIA", "STATE_RELIGION"),
    "CIVILIZATION_GREECE": ("REPUBLIC", "DESPOTISM", "SLAVERY", "MILITIA", "ANCESTOR_CULT"),
    "CIVILIZATION_PERSIA": ("MONARCHY", "DESPOTISM", "SLAVERY", "MILITIA", "STATE_RELIGION"),
    "CIVILIZATION_CARTHAGE": ("REPUBLIC", "PLUTOCRACY", "SLAVERY", "MILITIA", "STATE_RELIGION"),
    "CIVILIZATION_ROME": ("REPUBLIC", "DESPOTISM", "SLAVERY", "MILITIA", "STATE_RELIGION"),
    "CIVILIZATION_JAPAN": ("MONARCHY", "DESPOTISM", "SERFDOM", "KNIGHTHOOD", "ANCESTOR_CULT"),
    "CIVILIZATION_ETHIOPIA": ("MONARCHY", "DESPOTISM", "SERFDOM", "MILITIA", "STATE_RELIGION"),
    "CIVILIZATION_MAYA": ("MONARCHY", "THEOCRATIC_LEGITIMACY", "SLAVERY", "WARRIOR_SOCIETY", "STATE_RELIGION"),
    "CIVILIZATION_VIKING": ("MONARCHY", "DESPOTISM", "SERFDOM", "WARRIOR_SOCIETY", "ANCESTOR_CULT"),
    "CIVILIZATION_ARABIA": ("MONARCHY", "THEOCRATIC_LEGITIMACY", "SERFDOM", "MILITIA", "GOD_STATE"),
    "CIVILIZATION_KHMER": ("MONARCHY", "DESPOTISM", "SERFDOM", "MILITIA", "STATE_RELIGION"),
    "CIVILIZATION_SPAIN": ("MONARCHY", "DESPOTISM", "SERFDOM", "KNIGHTHOOD", "STATE_RELIGION"),
    "CIVILIZATION_FRANCE": ("MONARCHY", "DESPOTISM", "SERFDOM", "KNIGHTHOOD", "STATE_RELIGION"),
    "CIVILIZATION_ENGLAND": ("MONARCHY", "DESPOTISM", "SERFDOM", "KNIGHTHOOD", "STATE_RELIGION"),
    "CIVILIZATION_GERMANY": ("MONARCHY", "DESPOTISM", "SERFDOM", "KNIGHTHOOD", "STATE_RELIGION"),
    "CIVILIZATION_RUSSIA": ("MONARCHY", "DESPOTISM", "SERFDOM", "MILITIA", "STATE_RELIGION"),
    "CIVILIZATION_NETHERLANDS": ("REPUBLIC", "PLUTOCRACY", "CORPORATE_ECONOMY", "MILITIA", "TOLERANCE"),
    "CIVILIZATION_MALI": ("MONARCHY", "THEOCRATIC_LEGITIMACY", "SLAVERY", "MILITIA", "STATE_RELIGION"),
    "CIVILIZATION_PORTUGAL": ("MONARCHY", "THEOCRATIC_LEGITIMACY", "SERFDOM", "KNIGHTHOOD", "STATE_RELIGION"),
    "CIVILIZATION_INCA": ("MONARCHY", "THEOCRATIC_LEGITIMACY", "SERFDOM", "MILITIA", "STATE_RELIGION"),
    "CIVILIZATION_MONGOL": ("MONARCHY", "DESPOTISM", "SERFDOM", "KNIGHTHOOD", "ANCESTOR_CULT"),
    "CIVILIZATION_AZTEC": ("MONARCHY", "THEOCRATIC_LEGITIMACY", "SLAVERY", "WARRIOR_SOCIETY", "STATE_RELIGION"),
    "CIVILIZATION_OTTOMAN": ("MONARCHY", "THEOCRATIC_LEGITIMACY", "SERFDOM", "KNIGHTHOOD", "STATE_RELIGION"),
    "CIVILIZATION_AMERICA": ("REPUBLIC", "RULE_OF_LAW", "CORPORATE_ECONOMY", "PROFESSIONAL_ARMY", "TOLERANCE"),
    "CIVILIZATION_BYZANTIUM": ("MONARCHY", "THEOCRATIC_LEGITIMACY", "SERFDOM", "MILITIA", "GOD_STATE"),
}

DEFAULTS = ("TRIBAL_SYSTEM", "DESPOTISM", "SELF_SUFFICIENCY", "WARRIOR_SOCIETY", "ANCESTOR_CULT")
FALLBACKS = (
    ("MONARCHY", "TRIBAL_SYSTEM"),
    ("DESPOTISM",),
    ("SLAVERY", "SELF_SUFFICIENCY"),
    ("MILITIA", "WARRIOR_SOCIETY"),
    ("STATE_RELIGION", "ANCESTOR_CULT"),
)


def apply(iPlayer):
    # Resolve infos here, never during module import before XML is available.
    gc = CyGlobalContext()
    player = gc.getPlayer(iPlayer)
    civType = player.getCivilizationType()
    if civType < 0:
        return
    profile = PROFILES.get(gc.getCivilizationInfo(civType).getType(), DEFAULTS)
    for iColumn in range(len(profile)):
        for name in (profile[iColumn],) + FALLBACKS[iColumn]:
            civic = gc.getInfoTypeForString("CIVIC_" + name)
            if civic >= 0 and player.canDoCivics(civic):
                option = gc.getCivicInfo(civic).getCivicOptionType()
                if player.getCivics(option) != civic:
                    player.setCivics(option, civic)
                break
